services:
  readme.blog.postgres:
    image: postgres:14-alpine
    container_name: readme.blog.postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - readme.postgres.blog:/var/lib/postgresql/data

    healthcheck:
      test:
        ['CMD-SHELL', 'pg_isready', '--username', '${POSTGRES_USER}', '--dbname', '{POSTGRES_DB}']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s

    networks:
      - readme.blog

  readme.blog.pgadmin:
    image: dpage/pgadmin4
    container_name: readme.blog.pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - '8082:80'
    depends_on:
      readme.blog.postgres:
        condition: service_healthy
    networks:
      - readme.blog

volumes:
  readme.postgres.blog:

networks:
  readme.blog:
    driver: bridge
